from selenium.webdriver import Chrome
from time import sleep
driver = Chrome(executable_path = r"../drivers/chromedriver.exe")
driver.get("https://demowebshop.tricentis.com/")
#driver.get("https://www.swiggy.com/")
driver.maximize_window()
search=driver.find_element("name","q")
search.send_keys("shirts")
#driver.find_element("class","button-1.search-box-button").click()
#srchbtn=driver.find_element("type","submit")
#srchbtn.click()
driver.find_element("link text","Register").click()
sleep(5)
driver.find_element("name","Gender").click()
driver.find_element("id","FirstName").send_keys("TestFirstName")
driver.find_element("class","text-box single-line").send_keys("Testlastname")
driver.find_element("name","Email").send_keys("test@gmail.com")
driver.find_element("classname","text-box single-line password").send_keys("AniL@123")
driver.find_element("name","ConfirmPassword").send_keys("AniL@123")
driver.find_element("name","register-button").click()
